### ISSUE TITLE
Question: Why does the mapping need to be defined in the opposite direction when mapping expressions?

### ISSUE THREAD

**Issue by isak-spinit** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#134]
Hi,

If I want to map from `Expression<Func<Source, bool>>` to `Expression<Func<Destination, bool>>`,
why is it that the mapping configuration needs to be defined from Destination to Source (`cfg.CreateMap<Destination, Source>()`) and not the other way around? 

If I want to map an object of type `Source` to `Destination`, the mapping definition is `cfg.CreateMap<Source, Destination>()`.

The same question was asked here without a clear answer (https://github.com/AutoMapper/AutoMapper/issues/1807).

Thanks!

**Comment by BlaiseD** [comment]
Because that's where we get the new expression.  See [how the code works here](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/blob/4e85a57612768d407fa6ae8925c64d4a4bf199c4/src/AutoMapper.Extensions.ExpressionMapping/XpressionMapperVisitor.cs#L629).

And here's an [example](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/blob/4e85a57612768d407fa6ae8925c64d4a4bf199c4/tests/AutoMapper.Extensions.ExpressionMapping.UnitTests/XpressionMapper.Structs.Tests.cs#L151).
