### ISSUE TITLE
Cosmos DB LINQ provider with Odata sans EF

### ISSUE THREAD

**Issue by wbuck** [AutoMapper/AutoMapper.Extensions.ExpressionMapping#155]
Hi Blaise,

So, for the last couple of weeks I've been trying to use the `Cosmos DB` LINQ provider with Odata. 
I'm not using EF as it's generating incorrect SQL.

Anyway, some issues I've run into for example is that `$select` does not work (full stop).
I had to completely replace the `MethodCallExpression` representing the `Select` method call and generate a new runtime type in order to get that working.

Next, I created an `Expression` tree visitor which replaces all `Expression<TSource>` to `Expression<TDest>` expressions using `AutoMapper` for type mappings.

All works well, but I know that you have this repo as well this [repo](https://github.com/AutoMapper/AutoMapper.Extensions.OData) and I'm wondering if I'm just reinventing the wheel here.

<h3>Questions</h3>

1. Does this library depend on EF in anyway (think extension methods)?
2. Can I map an entire expression tree?

For example: 

     // Think of the expression tree generated from OData's ODataQueryOptions.ApplyTo method.
     sourceQuery = sourceQuery.Where(...).Select(...).OrderBy(...);
     var expression =  mapper.MapExpression<Source, Destination>(sourceQuery.Expression);

Granted, in the above example, I don't think that would work unless you also had a destination `IQueryable` to work with.

What I'm thinking of is to first apply the Odata query to the `CosmosEnumerable`, pass the `Expression` to the `mapper.MapExpression` and then use my `SelectReplacer` to replace the invalid `Select` `MethodCallExpression` with a valid one.
    
Or maybe I can use this library within my `Expression` visitor to map any `Expression<TSource>` to `Expression<TDest`.

I'm just not 100% sure on how this library is supposed to be used.

**Comment by BlaiseD** [comment]
The other library was started because of [questions](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/issues/3) about using this one with OData.

I would use the code [here](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/52ff5963221b33a126365d402a3c5e8e5efb2b88/AutoMapper.AspNetCore.OData.EFCore/QueryableExtensions.cs#L122) and [here](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/52ff5963221b33a126365d402a3c5e8e5efb2b88/AutoMapper.AspNetCore.OData.EFCore/QueryableExtensions.cs#L145) as a guide.

I'm pretty sure none of that is EF specific.  It's creating the selections and expansion from `ODataQueryOptions`.  I would test that against Cosmos DB and go from there.   The EF6 and EF libraries share much of the same code - maybe a third project targeting Cosmos DB might be in order if that makes sense  for you.

**Comment by wbuck** [comment]
@BlaiseD I'm going to make a feature request on the other repo. I'll start working on this (most of it is already done but I want to utilize a lot of the helpers already defined in both this repo and the other).

**Comment by BlaiseD** [comment]
[Feature request: Add support for CosmosDB](https://github.com/AutoMapper/AutoMapper.Extensions.OData/issues/166)
